# Generated by Django 3.2.15 on 2023-03-22 23:41

import authorisation.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/cat.jpg', null=True, upload_to=authorisation.utils.get_avatar_path, verbose_name='аватар'),
        ),
    ]
