[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.mypy]
mypy_path = "./lyceum"
python_version = 3.9
disallow_untyped_defs = true
exclude = "env.*|venv.*|migrations.*"
plugins = "mypy_django_plugin.main"
strict = true
ignore_missing_imports = true
explicit_package_bases = true

[tool.django-stubs]
django_settings_module = "lyceum.settings"

[tool.flake8]
max-line-length = "79"
plugins = "pep8-naming flake8-import-order flake8-quotes"
exclude = "venv"
ignore = "E203,E121,E123,E126,E226,E24,E704,W503,W504"
count = true
show-source = true
statistics = true

[tool.pylint]
disable = ["C0415"]
