[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.mypy]
mypy_path = "./lyceum"
python_version = 3.8
disallow_untyped_defs = true
exclude = "env.*|venv.*|migrations.*"
plugins = "mypy_django_plugin.main"
strict = true

[tool.django-stubs]
django_settings_module = "lyceum.settings"

[tool.flake8]
max-line-length = "79"
plugins = "pep8-naming flake8-import-order flake8-quotes"
<<<<<<< HEAD

[tool.pylint]
ignore = ["__init__.py"]
=======
>>>>>>> e96540ab8d1167c09bbab3e849053b21f7e6a121
