[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.django-stubs]
django_settings_module = "lyceum.lyceum.settings"

[tool.flake8]
max-line-length = "79"
plugins = "pep8-naming flake8-import-order flake8-quotes"