# Generated by Django 3.2.15 on 2023-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='uploads/cat.jpg', upload_to='', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.IntegerField(default=0, verbose_name='попыток сварить кофе'),
        ),
    ]
