# Generated by Django 3.2.15 on 2023-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230321_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/cat.jpg', null=True, upload_to='', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
