# Generated by Django 3.2.15 on 2023-03-30 14:05

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_rename_change_time_evaluation_change_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 14, 5, 40, 694591, tzinfo=utc), help_text='дата и время создания отзыва', verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='change_datetime',
            field=models.DateTimeField(auto_now=True, help_text='значение обновляется каждый раз, когда пользователь меняет свою оценку', verbose_name='дата и время изменения'),
        ),
    ]
