# Generated by Django 3.2.15 on 2023-03-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230323_1916'),
        ('catalog', '0012_alter_item_category'),
        ('rating', '0010_auto_20230330_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='item',
            field=models.ForeignKey(help_text='Товар, которому оставили отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='rating_item', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(help_text='Пользователь оставивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='users.userproxy', verbose_name='пользователь'),
        ),
    ]
