# Generated by Django 3.2.15 on 2023-02-21 20:44

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Да/Нет',
                        verbose_name='Опубликован',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Придумайте название',
                        max_length=150,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='Название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Придумайте артикул(может состоять только из латинских букв, цифр, _ и -)',
                        max_length=200,
                        unique=True,
                        validators=[
                            core.validators.slug_validator,
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name='Уникальный артикул',
                    ),
                ),
                (
                    'weight',
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name='Вес'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Да/Нет',
                        verbose_name='Опубликован',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Придумайте название',
                        max_length=150,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='Название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Придумайте артикул(может состоять только из латинских букв, цифр, _ и -)',
                        max_length=200,
                        unique=True,
                        validators=[
                            core.validators.slug_validator,
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name='Уникальный артикул',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Да/Нет',
                        verbose_name='Опубликован',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Придумайте название',
                        max_length=150,
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='Название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Опишите объект',
                        validators=[
                            core.validators.ValidateMustContain(
                                'превосходно', 'роскошно'
                            )
                        ],
                        verbose_name='Описание',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text='Выберите категорию',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='catalog.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        to='catalog.Tag', verbose_name='Тэги'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
