# Generated by Django 3.2.15 on 2023-02-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name='Вес'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='catalog.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.Tag', verbose_name='Тэги'
            ),
        ),
    ]
