# Generated by Django 3.2.15 on 2023-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                default='test',
                max_length=150,
                verbose_name='Нормализованное имя',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                default='test',
                max_length=150,
                verbose_name='Нормализованное имя',
            ),
            preserve_default=False,
        ),
    ]
