# Generated by Django 3.2.15 on 2023-03-01 10:10

import ckeditor.fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Опишите объект', validators=[core.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(default='uploads\\cat.jpg', help_text='Загрузите фото', upload_to='uploads/main_images/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(default='uploads\\cat.jpg', help_text='Загрузите фото', upload_to='uploads/gallery/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
