# Generated by Django 3.2.15 on 2023-02-21 08:35

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Придумайте артикул(может состоять только из латинских букв, цифр, _ и -)', max_length=200, unique=True, validators=[Core.validators.slug_validator], verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Опишите объект', validators=[Core.validators.rich_text_validator], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(help_text='Придумайте артикул(может состоять только из латинских букв, цифр, _ и -)', max_length=200, unique=True, validators=[Core.validators.slug_validator], verbose_name='Артикул'),
        ),
    ]
