# Generated by Django 3.2.15 on 2023-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                max_length=150, unique=True, verbose_name='Нормализованное имя'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                max_length=150, unique=True, verbose_name='Нормализованное имя'
            ),
        ),
    ]
