# Generated by Django 3.2.15 on 2023-02-21 17:05

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230221_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Придумайте название',
                max_length=150,
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(
                help_text='Придумайте артикул(может состоять только из латинских букв, цифр, _ и -)',
                max_length=200,
                unique=True,
                validators=[
                    core.validators.slug_validator,
                    django.core.validators.MaxLengthValidator(200),
                ],
                verbose_name='Уникальный артикул',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Придумайте название',
                max_length=150,
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Придумайте название',
                max_length=150,
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(
                help_text='Придумайте артикул(может состоять только из латинских букв, цифр, _ и -)',
                max_length=200,
                unique=True,
                validators=[
                    core.validators.slug_validator,
                    django.core.validators.MaxLengthValidator(200),
                ],
                verbose_name='Уникальный артикул',
            ),
        ),
    ]
