# Generated by Django 3.2.15 on 2023-03-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230302_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainImage',
        ),
    ]
