# Generated by Django 3.2.15 on 2023-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_mainimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', upload_to='uploads/gallery/', verbose_name='фото'),
        ),
    ]
