# Generated by Django 3.2.15 on 2023-03-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230302_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
    ]
