# Generated by Django 3.2.15 on 2023-03-03 20:06

import core.support
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_photogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='test', help_text='Загрузите фото', upload_to=core.support.get_upload_location, verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', upload_to=core.support.get_upload_location, verbose_name='фото'),
        ),
    ]
