# Generated by Django 3.2.15 on 2023-03-03 20:31

import core.support
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20230303_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', max_length=200, upload_to=core.support.get_upload_location, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(help_text='Загрузите фото', max_length=200, upload_to=core.support.get_upload_location, verbose_name='фото'),
        ),
    ]
