# Generated by Django 3.2.15 on 2023-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Да/Нет', verbose_name='Опубликован?')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
