# Generated by Django 3.2.15 on 2023-02-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
